from datetime import timedelta
from typing import Protocol, runtime_checkable


@runtime_checkable
class Cache[K, V](Protocol):
    async def get(self, key: K) -> V | None: ...
    async def set(self, key: K, value: V, expire: float | timedelta | None = None) -> None: ...
    async def exists(self, pattern: K) -> bool: ...
    async def delete(self, *keys: K) -> None: ...
    async def clear(self) -> None: ...
    async def close(self) -> None: ...
    async def set_list(
        self,
        key: K,
        *value: V,
        expire: float | timedelta | None = None,
    ) -> None: ...
    async def get_list(self, key: K) -> list[V]: ...
    async def discard(self, key: K, value: V) -> None: ...
    async def keys(self) -> list[K]: ...
    async def increment(self, key: K, amount: int = 1) -> int: ...
    async def decrement(self, key: K, amount: int = 1) -> int: ...


@runtime_checkable
class StrCache(Cache[str, str], Protocol): ...
